### ISSUE TITLE
UploadAttachment函数上传文件时错误

### ISSUE THREAD

**Issue by qq992936** [fox-one/mixin-sdk-go#4]
UploadAttachment函数调用后返回错误：
X-Request-Id mismatch, expect "62aa8c13-f7c2-40ce-b62b-4b17e772159d" but got ""

**Comment by yiplee** [comment]
感谢反馈

**Comment by qq992936** [comment]
ok

**Comment by yiplee** [comment]
v1.0.4 修复了这个问题
