### ISSUE TITLE
关于使用ReadSnapshots接口的问题

### ISSUE THREAD

**Issue by RandyLambert** [fox-one/mixin-sdk-go#7]
为什么我使用该函数获取我自己的交易记录,记录里有opponent_id但是没有返回user_id
  {
        "snapshot_id": "b2feb56b-91a9-4325-be19-4e6a23223045",
        "created_at": "2020-07-16T13:25:16.601114Z",
        "trace_id": "6fa359dc-@@@@-@@@@-@@@@-1a46b2e19717",
        "asset_id": "815b0b1a-2764-3736-8faa-42d694fa620a",
        "opponent_id": "@@@4a693-@@@@-@@@@-@@@@-c7dfef844126",
        "amount": "0.0001",
        "opening_balance": "*.@@@@",
        "closing_balance": "*.@@@@-",
        "memo": "pong",
        "type": "transfer"
    }

**Comment by yiplee** [comment]
/snapshots 这个接口是获取自己的转账记录，api 那边是不返回 snapshot.user_id 的。 你可以通过 client.ClientID 获取自己的 user id
