### ISSUE TITLE
[Bug] Transaction /transactions doesn't return snapshot_id

### ISSUE THREAD

**Issue by Halimao** [fox-one/mixin-sdk-go#72]
Maybe this should be "snapshot_id"? [source_code](https://github.com/fox-one/mixin-sdk-go/blob/master/transaction_raw.go#L13)
![image](https://user-images.githubusercontent.com/25278203/158009746-7772267a-aef7-472b-a873-fe97eb22e0e7.png)
![image](https://user-images.githubusercontent.com/25278203/158009773-6829ccc0-98a3-4e10-801a-1e073b2752cd.png)

**Comment by yiplee** [comment]
fixed in commit [#3d5b1891317fd821269a016d397b0eddd2d5fe3c](https://github.com/fox-one/mixin-sdk-go/commit/3d5b1891317fd821269a016d397b0eddd2d5fe3c)

**Comment by Halimao** [comment]
cool
